### ISSUE TITLE
DefaultAuthenticator#toCanonicalizeHeaderValue creates and compiles a Regex pattern for each header

### ISSUE THREAD

**Issue by benbenw** [Ingenico-ePayments/connect-sdk-java#10]
Re-use the pattern which is thread safe
Reduce cpu usage.

**Comment by rob-spoor** [comment]
This is fixed in version 5.18.1 and up. Only version 5.18.3 managed to find its way to Maven Central though, so please use that version.

**Comment by rob-spoor** [comment]
FYI, there is no need to create an additional issue if you've already created a pull request.

**Comment by benbenw** [comment]
ok
Some projects require an issue.
