### ISSUE TITLE
Invalid URI in description

### ISSUE THREAD

**Issue by pcoenen** [Ingenico-ePayments/connect-sdk-java#15]
https://epayments.developer-ingenico.com/documentation/sdk/java/ gives a 404

**Comment by rob-spoor** [comment]
Can you please tell me where you found this URL? I have checked the source but could find no occurrences. I did find one occurrence of the correct URL, https://epayments.developer-ingenico.com/documentation/sdk/server/java/, in README.md.

**Comment by pcoenen** [comment]
In the header of the github page 

![image](https://user-images.githubusercontent.com/17742895/41974789-35c60040-7a19-11e8-880d-c2bd827f338e.png)

**Comment by rob-spoor** [comment]
You're right, we missed that. We will have this fixed ASAP.
