### ISSUE TITLE
Hosted Checkouts integration with Sofort returns http 500

### ISSUE THREAD

**Issue by eduard-tuduri** [Ingenico-ePayments/connect-sdk-java#16]
I'm trying to integrate with Sofort payment method using Hosted Checkouts on the sandbox environment. When I select Sofort payment, I expect a redirect to Sofort, but it instantly returns me to my page with a HTTP Code 500, payment status "REJECTED",  error message: "Exception, invalid data" and error code: 15000960. I've tested my application with other redirect payment methods such as PayPal, iDEAL and it works fine.

**Comment by rob-spoor** [comment]
The cause lies not in the SDK, but instead in the Ingenico ePayments platform. I suggest you contact Ingenico about this error.
