### ISSUE TITLE
Wrong behaviour on "Authorization - Pending" test case

### ISSUE THREAD

**Issue by LucasStadelmann** [Ingenico-ePayments/connect-sdk-java#17]
Refer to your "test cases" documentation for Visa or MasterCard, there is 3 amount dedicated for testing declined payment authorization:
- 12.04 € for "Uncertain",
- 13.04 € for "Refused" and
- 14.04 € for "Pending"

When these test cases thrown a ResponseException, you catch it in **PaymentsClient**, line 101.

In 12.04 € & 13.04 € cases, the ResponseException has a status code of 402.

So we fall into an errorType of **PaymentErrorResponse.class** :
`errorType = PaymentErrorResponse.class;` (PaymentsClient line 108)

And finally your client return a **DeclinedPaymentException** in **ApiResource** line 80 :
`return new DeclinedPaymentException(statusCode, responseBody, (PaymentErrorResponse) errorObject);`

That allow us to retrieve informations about the declined payment in the **CreatePaymentResult**.

But with 14.04 € case, the ResponseException has a status code of 500.

So it fall into default errorType wich is **ErrorResponse.class** :
`errorType = ErrorResponse.class;` (PaymentsClient line 120)

And finally your client return a **GlobalCollectException** in **ApiResource** line 131 :
`return new GlobalCollectException(statusCode, responseBody, errorId, errors);`

But as shown in the response body of the 14.04 € test case :

```
com.ingenico.connect.gateway.sdk.java.GlobalCollectException: the Ingenico ePayments platform returned an error response;
statusCode=500;
responseBody='{
   "errorId" : "5ba21df82753eab725a956f4424d3726",
   "errors" : [ {
      "code" : "9999",
      "id" : "UNKNOWN_SERVER_ERROR",
      "category" : "CONNECT_PLATFORM_ERROR",
      "message" : "UNKNOWN_SERVER_ERROR",
      "httpStatusCode" : 500
   } ],
   "paymentResult" : {
      "payment" : {
         "id" : "xxxxxxxxxx_x",
         "paymentOutput" : {
            "amountOfMoney" : {
               "amount" : 1404,
               "currencyCode" : "EUR"
            },
            "references" : {
               "merchantReference" : "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
            },
            "paymentMethod" : "card",
            "cardPaymentMethodSpecificOutput" : {
               "paymentProductId" : 1,
               "fraudResults" : {
                  "fraudServiceResult" : "accepted"
               },
               "threeDSecureResults" : {
                  "eci" : "9"
               },
               "card" : {
                  "cardNumber" : "XXXXXXXXXXXXXXXX",
                  "expiryDate" : "XXXX"
               },
               "token" : "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
            }
         },
         "status" : "REJECTED",
         "statusOutput" : {
            "isCancellable" : false,
            "statusCategory" : "UNSUCCESSFUL",
            "statusCode" : 2,
            "isAuthorized" : false,
            "isRefundable" : false
         }
      }
   }
}'
```

There is a payment result, so the status code should be 402 to allow us to retrieve informations about the declined payment.

**Comment by rob-spoor** [comment]
This code is generated from the API references, so any error that's not described there will not be part of the generated code.
In this case, all of the documented error cases have PaymentErrorResponse as the return type. That indeed makes it nonsensical to default to the more generic ErrorResponse. We should change the generation so that if there is only one different error response type possible (in this case PaymentErrorResponse), that it will default to this error type.

**Comment by LucasStadelmann** [comment]
Ok, but there is still something anormal.

In your API Explorer (Web application), when I call Create Payment (POST /v1/{merchandId}/payments) with the 14.04 € test case, the status code is effectively 402 :

Request body :
```
{
	"order": {
		"amountOfMoney": {
			"amount": 1404,
			"currencyCode": "EUR"
		},
		"references": {
			"merchantReference": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
		}
	},
	"cardPaymentMethodSpecificInput": {
		"token": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
		"skipAuthentication": true,
		"isRecurring": true,
		"recurringPaymentSequenceIndicator": "recurring",
		"transactionChannel": "ECOMMERCE",
		"paymentProductId": 1,
		"returnUrl": "http://localhost/"
	}
}
```

Response body :
```
{
   "errorId" : "5ba26044574a1c97fa14f2af0b15bc74",
   "errors" : [ {
      "id" : "EXTERNAL_ACQUIRER_ERROR",
      "category" : "IO_ERROR",
      "httpStatusCode" : 402
   } ],
   "paymentResult" : {
      "payment" : {
         "id" : "3040373143_0",
         "paymentOutput" : {
            "amountOfMoney" : {
               "amount" : 1204,
               "currencyCode" : "EUR"
            },
            "references" : {
               "merchantReference" : "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
            },
            "paymentMethod" : "card",
            "cardPaymentMethodSpecificOutput" : {
               "paymentProductId" : 1,
               "fraudResults" : {
                  "fraudServiceResult" : "accepted"
               },
               "threeDSecureResults" : {
                  "eci" : "9"
               },
               "card" : {
                  "cardNumber" : "XXXXXXXXXXXXXXXX",
                  "expiryDate" : "XXXX"
               },
               "token" : "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
            }
         },
         "status" : "REJECTED",
         "statusOutput" : {
            "isCancellable" : false,
            "statusCategory" : "UNSUCCESSFUL",
            "statusCode" : 2,
            "isAuthorized" : false,
            "isRefundable" : false
         }
      }
   }
}
```

So why, in the Java SDK, do we receive a status code 500 in the **ResponseException** in the 14.04 € test case.

**Comment by rob-spoor** [comment]
That is something that is impossible to tell without checking the log files. Please contact Ingenico about this. Provide them with the time frame this happened and the error id (5ba21df82753eab725a956f4424d3726).

**Comment by LucasStadelmann** [comment]
Ok fine, thanks for explanation.
