### ISSUE TITLE
Antivirus alert when downloading connect-sdk-java-6.3.0-bin.zip from releases

### ISSUE THREAD

**Issue by jrmasis** [Ingenico-ePayments/connect-sdk-java#19]
Hello, I receantly tried to download the connect-sdk-java-6.3.0-bin.zip from https://github.com/Ingenico-ePayments/connect-sdk-java/releases and a collegue antivirus and mine poped up an alert, just wanted to let you know about it.

**Comment by rob-spoor** [comment]
This is most likely a false positive. I have just uploaded the file to https://www.virustotal.com/gui/home/upload, both as a file and as a URL, and it found no issues. Perhaps you can contact your antivirus software provider. Most have some form of uploading files that triggered false positives.
