### ISSUE TITLE
SDK availablilty in maven central repository

### ISSUE THREAD

**Issue by nishanv** [Ingenico-ePayments/connect-sdk-java#2]
Hi team

When can we expect the java sdk in maven central repository?

**Comment by ebomcke-ingenico** [comment]
Hi,
The jar will be published in the central repository in the coming month, I'll update this issue when it has been done.

**Comment by hoikin** [comment]
now is 2017 and still cannot find in central repo

**Comment by ebomcke-ingenico** [comment]
The priority of this task was reduced since that last comment, as a result it was completed later than initially thought. The jar has been published now, see https://repo1.maven.org/maven2/com/ingenico/connect/gateway/connect-sdk-java/.

**Comment by hoikin** [comment]
thx
