### ISSUE TITLE
Question Regarding Importing The SDK using sbt

### ISSUE THREAD

**Issue by avshRepo** [Ingenico-ePayments/connect-sdk-java#20]
I am trying to get dependency using sbt. what should i put in the libraryDependencies
i tried 
    libraryDependencies += "com.ingenico.connect.gateway" %% "connect-sdk-java" % "1.0.34"

but got error in dependency resolution

**Comment by rob-spoor** [comment]
That's because there is no version 1.0.34. The SDK went directly from version 1.0.0 to 2.0.0. The current version is 6.4.0, so I would suggest using that.
