### ISSUE TITLE
Missing fields

### ISSUE THREAD

**Issue by AlexGianq** [Ingenico-ePayments/connect-sdk-java#22]
Hi!
I'm using the SDK feature by feature, and for now I'm having missing fields on several objects:
- `CreateHostedCheckoutResponse.redirectUrl`
- `GetHostedCheckoutResponse.createdPaymentOutput.payment.paymentOutput.references.merchantParameters`
Maybe there are more, but for now I'm stuck with this parameters being absent from the model.

**Comment by worldline-direct-support-team** [comment]
Hi @AlexGianq, it looks like you are trying to use fields that are not available in Connect. 

Are you using the right SDK? This SDK is for communicating with the Connect API, but these fields belong to the [Direct API](https://support.direct.ingenico.com/documentation/api/reference).

If you are integrating with Direct you can use the [Direct Java SDK](https://github.com/wl-online-payments-direct/sdk-java).

**Comment by AlexGianq** [comment]
Hi back.
I think you're right, I did not notice because many fields and methods are in common.
I'll check the other one then.
Regards

**Comment by rob-spoor** [comment]
@AlexGianq has your issue been resolved?
