### ISSUE TITLE
Are there plans to release a non-blocking version of this SDK?

### ISSUE THREAD

**Issue by nicojanssens** [Ingenico-ePayments/connect-sdk-java#4]
Hi,

I'd like to integrate the java sdk into a reactive stack. Unfortunately, the code in this repo seems to include blocking calls. Are there plans to release a non-blocking version in the near future, using for instance [Play's WS library](https://www.playframework.com/documentation/2.5.x/JavaWS)?

Thanks.

**Comment by rob-spoor** [comment]
There are no plans for any non-blocking versions at this moment. However, it's already possible to create your own CompletionStages using `CompletableFuture.runAsync` and `CompletableFuture.supplyAsync`.
