### ISSUE TITLE
Signature fails for some JMV Locale

### ISSUE THREAD

**Issue by benbenw** [Ingenico-ePayments/connect-sdk-java#6]
DefaultAuthenticator authentication should not depend on the default JVM Locale
The current implementation will not generate the same signature based on the jvm default locale

Example :
if your jvm is set to the tr locale (running with _-Duser.language=tr_ or changing the os language)
then the connect server will reject the api call (`MISSING_OR_INVALID_AUTHORIZATION`)

**Comment by rob-spoor** [comment]
This is fixed in version 5.18.1 and up. Only version 5.18.3 managed to find its way to Maven Central though, so please use that version.
